### ISSUE TITLE
cleaning databse

### ISSUE THREAD

**Issue by amejiarosario** [ramonvictor/rv-protractor#12]
Hi Ramon,

I found your slides very useful. I have an issue with protractor and I'm wondering if you have any insight. What's the best way to clean the database before each protractor test suite run?? Data in forms start to pile up from old tests and it makes recent tests to fail...

**Comment by rafaelbattesti** [comment]
Hi Adrian. I used to have similar issues. In a testing environment, I used
to load a dbdump.sql before the tests to setup the environment, maybe one
idea is to save a dump.sql of the previous state of the database and reload
it when the tests are done.
Sounds like a plan? Good luck!

Cheers, Rafael.

**Comment by amejiarosario** [comment]
@rafaelbattesti thanks for your idea. However, I'm using mongodb. I'm think about using a more general solution with [node-database-cleaner](https://github.com/emerleite/node-database-cleaner). But, wondering about the best places to do that (grunt, protractor.conf's `onPrepare`)?

**Comment by rafaelbattesti** [comment]
Hi Adrian.

There's a way to dump your mongo database as well, find it here.

http://docs.mongodb.org/manual/tutorial/backup-and-restore-tools/

You can always use node's file system native module to generate child
processes and dump your mongodb before starting the tests in `onPrepare`
and then restore it after your tests are done, using an `it` block as the
last test case. That's the way I found to work around the database
restoration, but it's a hack.

@julimr explains how to use protractor.conf to run setup/teardown
configuration. You can use `jasmineNodeOpts.onComplete`.

https://github.com/angular/protractor/issues/103

Find more documentation about mongodb dump and restore here.

http://docs.mongodb.org/v2.2/tutorial/backup-databases-with-binary-database-dumps/

I do not exactly know how the node-database-cleaner works and the
documentation does not help either. ;-)

Hope this helps.

**Comment by amejiarosario** [comment]
Thanks for the links... My approach is a little different since I have 3 databases environments (test, development and production) so I'm not concern about backing up and restoring test db. Tests database should be clean on every run. I ended up adding a script that cleans the database just after the connection is open if it is in the test environment https://github.com/amejiarosario/meanshop/commit/23cf2e29c3c9e5e93a5461a6a0435fe08250b4c1
